# ────────────────────────────────────────────────────────────
# Omarchy Felix Theme for Alacritty
# By Ty Richards
# https://github.com/TyRichards
# ────────────────────────────────────────────────────────────

[window]
# window padding {px}
padding.x = 45
padding.y = 40
decorations = "none"

[font]
size = 12.0



[colors]
[colors.primary]
background = "#000000"
foreground = "#e7e9ea"
dim_foreground = "#8a8a8d"

[colors.cursor]
text = "#000000"
cursor = "#e7e9ea"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#e7e9ea"

[colors.selection]
text = "#000000"
background = "#e7e9ea"

[colors.normal]
black = "#000000"
red = "#e7e9ea"
green = "#e7e9ea"
yellow = "#e7e9ea"
blue = "#e7e9ea"
magenta = "#e7e9ea"
cyan = "#e7e9ea"
white = "#e7e9ea"

[colors.bright]
black = "#000000"
red = "#e7e9ea"
green = "#e7e9ea"
yellow = "#e7e9ea"
blue = "#e7e9ea"
magenta = "#e7e9ea"
cyan = "#e7e9ea"
white = "#e7e9ea"
